
import React, { useState, useRef, useEffect } from 'react';
import { ProjectData, ScriptBlock, ScriptBlockType, AppLanguage } from '../../types';
import { GeminiService } from '../../services/geminiService';
import { 
  Download, Undo, Redo, Zap, Save, FileText, Sparkles, 
  Plus, Trash2, ChevronDown, Wand2, Type as TypeIcon, 
  MoreHorizontal, MessageSquare, User, Clapperboard, 
  ArrowRight, Loader2, Printer, AlignCenter, AlignLeft, 
  Type, Info
} from 'lucide-react';

// Short Drama Format Styles
// Everything is generally left-aligned.
const getClassForType = (type: ScriptBlockType) => {
  switch (type) {
    case ScriptBlockType.SCENE_HEADING: 
      // Example: 1-1 宣朝京郊神秘山洞 夜 外
      return "font-mono font-bold text-lg text-ink-100 uppercase mb-2 mt-8 tracking-tight text-left";
    case ScriptBlockType.ACTION: 
      // Example: △谢无昀扶着洞口... OR 人物：谢无昀
      return "text-ink-200 text-base mb-2 leading-relaxed font-sans text-left w-full";
    case ScriptBlockType.CHARACTER: 
      // Kept for compatibility, but mapped to a simple bold left label if used
      return "text-ink-100 font-bold text-base mb-1 w-full text-left mt-4";
    case ScriptBlockType.PARENTHETICAL: 
      // Not strictly used in the new format (merged into Dialogue line), but kept for legacy
      return "text-ink-400 italic text-sm mb-1 w-full text-left";
    case ScriptBlockType.DIALOGUE: 
      // Example: 谢无昀（试探）：姑娘？
      // Left aligned, distinct color, standard width
      return "text-ink-100 text-base mb-2 leading-relaxed w-full text-left font-serif";
    case ScriptBlockType.TRANSITION: 
      return "font-bold text-ink-300 text-sm text-right my-6 uppercase";
    default: 
      return "text-base mb-4";
  }
};

export const ScriptEditor: React.FC<{ 
  data: ProjectData, 
  update: (data: Partial<ProjectData>) => void, 
  undo: () => void, 
  redo: () => void, 
  language: AppLanguage 
}> = ({ data, update, undo, redo, language }) => {
  const [isSynthesizing, setIsSynthesizing] = useState<string | null>(null);
  const [activeMenuId, setActiveMenuId] = useState<string | null>(null);

  const handleExport = () => {
    let text = `${data.title}\n\n`;
    data.script.forEach(b => {
      text += `${b.content}\n`;
      if (b.type === ScriptBlockType.SCENE_HEADING) text += `\n`;
    });
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.title}_短剧剧本.txt`;
    a.click();
  };

  const insertBlock = (atIndex: number, type: ScriptBlockType) => {
    const newBlock: ScriptBlock = {
      id: crypto.randomUUID(),
      type: type,
      content: ''
    };
    const newScript = [...data.script];
    newScript.splice(atIndex + 1, 0, newBlock);
    update({ script: newScript });
  };

  const deleteBlock = (id: string) => {
    if (data.script.length <= 1) return;
    update({ script: data.script.filter(b => b.id !== id) });
  };

  return (
    <div className="h-full flex flex-col bg-ink-950 relative overflow-hidden transition-colors duration-500">
      {/* 顶部工具栏 */}
      <div className="h-16 bg-ink-900 border-b border-ink-800 flex items-center justify-between px-8 shrink-0 z-30 shadow-sm transition-colors duration-500">
        <div className="flex items-center gap-4">
           <div className="flex bg-ink-950 rounded-lg p-1 border border-ink-800">
              <button onClick={undo} className="p-2 text-ink-400 hover:text-ink-100 hover:bg-ink-800 rounded transition-all"><Undo size={16} /></button>
              <button onClick={redo} className="p-2 text-ink-400 hover:text-ink-100 hover:bg-ink-800 rounded transition-all"><Redo size={16} /></button>
           </div>
           <div className="h-6 w-px bg-ink-800 mx-2"></div>
           <span className="text-[10px] font-bold text-ink-500 uppercase tracking-widest">短剧极简模式</span>
        </div>

        <div className="flex items-center gap-4">
           <button onClick={handleExport} className="flex items-center gap-2 px-5 py-2.5 bg-ink-100 text-ink-900 rounded-xl text-xs font-bold hover:bg-white transition-all shadow-lg border border-ink-200">
             <Download size={16} /> 导出文本
           </button>
        </div>
      </div>

      {/* 仿真页面 - 改为适合短剧阅读的流式布局，非传统A4 */}
      <div className="flex-1 overflow-y-auto py-12 px-4 custom-scrollbar bg-ink-950 transition-colors duration-500">
        <div className="max-w-3xl mx-auto bg-white min-h-[1000px] p-12 md:p-16 relative transition-transform animate-fadeIn shadow-2xl">
          
          <div className="mb-10 text-center border-b border-gray-100 pb-4">
             <h1 className="text-3xl font-black text-gray-900 mb-2">{data.title}</h1>
             <p className="text-xs text-gray-400 uppercase tracking-widest">剧本正文 • Generated by Inkflow</p>
          </div>

          {data.script.map((block, index) => (
            <div key={block.id} className="group relative mb-1">
               {/* 块悬浮操作台 */}
               <div className="absolute -left-16 top-1 opacity-0 group-hover:opacity-100 transition-all flex flex-col items-center gap-1">
                  <button 
                    onClick={() => setActiveMenuId(activeMenuId === block.id ? null : block.id)}
                    className="p-1.5 bg-gray-100 text-gray-400 hover:text-blue-600 rounded-lg transition-all"
                  >
                    <TypeIcon size={12} />
                  </button>
                  {activeMenuId === block.id && (
                    <div className="absolute left-full ml-2 top-0 bg-white p-2 rounded-xl border border-gray-200 shadow-2xl flex flex-col gap-1 z-50 w-32">
                      {[
                        { label: '场景行 (1-1)', type: ScriptBlockType.SCENE_HEADING },
                        { label: '动作 (△)', type: ScriptBlockType.ACTION },
                        { label: '对话 (Name:)', type: ScriptBlockType.DIALOGUE },
                      ].map(t => (
                        <button 
                          key={t.type}
                          onClick={() => { update({ script: data.script.map(b => b.id === block.id ? { ...b, type: t.type } : b) }); setActiveMenuId(null); }}
                          className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all ${block.type === t.type ? 'bg-blue-600 text-white' : 'text-gray-500 hover:bg-gray-100'}`}
                        >
                          {t.label}
                        </button>
                      ))}
                    </div>
                  )}
                  <button onClick={() => deleteBlock(block.id)} className="p-1.5 bg-gray-100 text-gray-400 hover:text-red-500 rounded-lg transition-all">
                    <Trash2 size={12} />
                  </button>
                  <button 
                    onClick={() => insertBlock(index, ScriptBlockType.ACTION)}
                    className="p-1.5 bg-gray-100 text-gray-400 hover:text-green-600 rounded-lg transition-all"
                  >
                    <Plus size={12} />
                  </button>
               </div>

               <textarea
                 value={block.content}
                 onChange={(e) => update({ script: data.script.map(b => b.id === block.id ? { ...b, content: e.target.value } : b) })}
                 className={`w-full bg-transparent resize-none outline-none overflow-hidden whitespace-pre-wrap transition-all ${getClassForType(block.type)} rounded-sm`}
                 rows={1}
                 style={{ height: 'auto', minHeight: '1.5em' }} 
                 onInput={(e: any) => {
                   e.target.style.height = 'auto';
                   e.target.style.height = e.target.scrollHeight + 'px';
                 }}
                 placeholder={block.type === ScriptBlockType.SCENE_HEADING ? "1-1 场景..." : "..."}
               />
            </div>
          ))}
          
          <div className="h-32 flex flex-col items-center justify-center border-t border-dashed border-gray-200 mt-20 opacity-50 hover:opacity-100 transition-opacity cursor-pointer" onClick={() => insertBlock(data.script.length - 1, ScriptBlockType.SCENE_HEADING)}>
             <div className="flex items-center gap-2 text-[10px] font-bold text-gray-400 uppercase tracking-[0.2em] hover:text-blue-600 transition-all">
                <Plus size={14} /> 点击添加新场次
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};
